# Generated by Django 4.0.10 on 2023-12-08 21:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_alter_freelancerformfield_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerpage',
            name='portfolio',
            field=wagtail.fields.StreamField([('portfolio', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('intro', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
