version: '3.9'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: web4${COMPOSE_PROJECT_NAME}
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
        - DJANGO_SETTINGS_MODULE=config.settings.dev
    restart: always

volumes:
  static_volume:
  media_volume:
