version: '3.9'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
      network: host
    container_name: web4${COMPOSE_PROJECT_NAME}_prod
    command: >
      sh -c "python3 manage.py migrate --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
        - DJANGO_SETTINGS_MODULE=config.settings.production
        - WEB_CONCURRENCY=3
        - GUNICORN_CMD_ARGS="--max-requests 1200 --access-logfile -"
    restart: always

volumes:
  static_volume:
  media_volume:
