# Base image
FROM python:3.10-slim-buster

ENV APP_HOME /app
ENV NODE_MAJOR 20

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH $APP_HOME

# Install operating system dependencies.
RUN apt-get update -y && \
    apt-get install -y apt-transport-https git rsync gettext libgettextpo-dev ca-certificates curl gnupg && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | \
    tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update -y && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

# create directory for the app user
RUN mkdir -p $APP_HOME

# don't run as root therefore create non-root user
RUN groupadd --gid 1000 appuser && \
    useradd --uid 1000 --gid appuser --home $APP_HOME appuser

# create the appropriate directories
RUN mkdir /staticfiles
RUN mkdir /mediafiles
WORKDIR $APP_HOME

# Copy project
COPY . $APP_HOME/

# Install Gunicorn.
RUN pip install "gunicorn>=19.8,<19.9"

# Install Python requirements.
RUN pip install -r requirements.txt

# chown all the files to the app user
RUN chown -R appuser:appuser $APP_HOME
RUN chown -R appuser:appuser /staticfiles
RUN chown -R appuser:appuser /mediafiles

# change to the app user
USER appuser
